jobs:
- job: windows
  strategy:
    maxParallel: 4
    matrix:
      x64:
        BUILD_ARCH: x64
        PLATFORM: x64
      x86:
        BUILD_ARCH: x86
        PLATFORM: x86
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      get-source.cmd
    displayName: Get libimobiledevice source code
  - script: |
      %VCPKG_INSTALLATION_ROOT%\vcpkg version
      %VCPKG_INSTALLATION_ROOT%\vcpkg integrate install
      echo.set(VCPKG_BUILD_TYPE %CONFIGURATION%)>> %VCPKG_INSTALLATION_ROOT%\triplets\%BUILD_ARCH%-windows.cmake
      cat %VCPKG_INSTALLATION_ROOT%\triplets\%BUILD_ARCH%-windows.cmake
      %VCPKG_INSTALLATION_ROOT%\vcpkg install libiconv:%BUILD_ARCH%-windows zlib:%BUILD_ARCH%-windows openssl:%BUILD_ARCH%-windows dirent:%BUILD_ARCH%-windows getopt:%BUILD_ARCH%-windows curl:%BUILD_ARCH%-windows libzip:%BUILD_ARCH%-windows
    displayName: Install dependencies
  - task: MSBuild@1
    inputs:
      solution: 'libimobiledevice-vs.sln' 
      platform: $(PLATFORM)
      configuration: Release
    displayName: 'Release build'